version: "1"
title: "IONe VDC"
context:
instances_groups:
  - type: ione
    title: Demo
    resources:
      ips_public: 1
    instances:
      - title: master-vm
        config:
          template_id: 15
          password: sup3rS3cr3tP4$$W0rD
        resources:
          cpu: 1
          ram: 1024
          drive_type: SSD
          drive_size: 13000
          ips_public: 1
          ips_private: 0